version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./source:/app
      - /app/node_modules # ホストのnode_modulesをオーバーライドしてコンテナ内のものを使用
    working_dir: /app
    command: npm run dev
